### ISSUE TITLE
Issue with E-values in the MySQL database

### ISSUE THREAD

**Issue by ulad-litvin** [giffordlabcvr/DIGS-tool#2]
I was trying to extract E-values for DIGS hits and noticed that there are two columns for E-value in the digs_resuts: **evalue_num** and **evalue_exp**. It looks like E-value is split into numerical and exponential parts when it is found in the form like 3e-15, so that **evalue_num** = 3 and **evalue_exp** = 15. In other cases (e.g. when E-value is 0.001) it is supposed to be stored in the **evalue_num** (**evalue_num** = 0.001) while **evalue_exp** = 1.
 
However, all **evalue_num** in the digs_resuts table are **integer** numbers (not floating-point numbers). It causes a problem. Since BLAST assigns E-value of 0.0 to all E-values below 1e-180 and DIGS loses information about E-values with floating point, now I have the same **evalue_num = 0** and **evalue_exp = 1** for hits with extremely high bitscore (>498) and extremely low (<30).

<img width="269" alt="e-value_issue_in_digs_results" src="https://github.com/giffordlabcvr/DIGS-tool/assets/124574161/0aa63337-e33b-43d2-939f-0a1176641fae">

**Comment by robjgiff** [comment]
Thanks for bringing this to my attention. I hadn't noticed this. In truth I have never used evalues for interrogating my own DIGS results, relying instead on bitscore. It shouldn't be a problem to fix, however. The reason for splitting the evalue into numerical and exponent components was that otherwise some results have extremely long floating point numbers that cause a problem for mysql. I wasn't entirely happy with the solution when implementing DIGS but it was the best I could come up with at the time. Any case, evalue_num should obviously be stored using a FLOAT or DOUBLE type, and I'll address that ASAP. Thanks again.

**Comment by robjgiff** [comment]
I've updated the DIGS code so that the 'evalue_num' field now records floating point numbers, not integers. You shouldn't need to recreate your screening database for this change to take effect, since the field type was correctly defined as a float in the 'digs_results' table - the issue was in the way this value was being captured prior to recording in the table. 
Thanks again for bringing the problem to my attention.
