### ISSUE TITLE
Bitscore threshold does not work

### ISSUE THREAD

**Issue by ulad-litvin** [giffordlabcvr/DIGS-tool#3]
Hi. I've recently updated DIGS to the latest version from GitHub and noticed that the bitscore threshold is no longer working. Now digs_results table in the MySQL database contains all DIGS hits, no matter whether their bitscore is higher than the threshold specified in the control file or not. For instance, here is what I found in my digs_results table after I specified the bitscore of 31 as the threshold. Before that, I was using the DIGS version that I installed from GitHub in January 2023. It was the latest version back then and the bitscore threshold worked fine. Thanks a lot!

<img width="727" alt="bitscore_threshold_not_working" src="https://github.com/giffordlabcvr/DIGS-tool/assets/124574161/da0888c1-dfeb-42d5-bcfa-6dbc75632dbc">

**Comment by robjgiff** [comment]
Thanks for raising this issue. I've tested bitscore threshold and it seems to be working. I wonder if the issue here is related to changes in your reference library? The bitscore that is recorded in the results table is not the one to which a threshold is applied. Bitscore threshold is applied to matches arising from the forward BLAST (probes versus target). The bitscore that is recorded in the results table is from the reverse BLAST (hit versus reference library). I have added console feedback under the 'verbose' flag that shows details of hits arising from forward BLAST that are excluded due to bitscore threshold: e.g.:

	  tblastn: 55: 'Apteryx_haastii' (GCA_003342985.1_aptHaa1, low_coverage)
	  target: 'GCA_003342985.1_aptHaa1_genomic.fna'
	  probe:  'Nairo_nucleocapsid'
		 # 1 matches to probe: Nairo, nucleocapsid
		 # Excluding hit below bitscore threshold (threshold = 60, bitscore = 34.7)
		 # 0 matches above threshold (excluded: 0 < length; 1 < bitscore)
		 # 0 previously extracted ORF loci
		 # 0 cross-matched to something other than the probe
		 # done 55 of 5537 queries (%0.99)

There is a reason that bitscore and other details from forward BLAST searches are not recorded, which is that defragmentation is performed on forward hits. Thus, individual rows in the results table can be the product of >1 forward BLAST.

I greatly appreciate feedback. Please let me know if this response explains your results, or if you think there may still be a problem.

**Comment by ulad-litvin** [comment]
Thanks a lot! I think you are right. The bitscore threshold works the same way as it used to work. I've tested it using DIGS v1.0.3. It makes sense that the bitscores in the digs_results table can be lower than the threshold since they come from the reverse BLAST (and the reference library is smaller than the genome library used for the forward BLAST). Thanks again! It really helped!

**Comment by robjgiff** [comment]
No problem! Please do let me know if you run into any other issues using DIGS or have feedback. 
-r
